name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    - name: Log into registry
      uses: docker/login-action@v2
      with:
        username: karlostcp
        password: ${{ secrets.MI_PTA_DOCKERHUB2 }}
